[package]
name = "simulator"
version = "0.3.0"
edition = "2024"

[dependencies]
bingo = { path = "../bingo" }
owo-colors = "*"
rand = "*"
rand_chacha = "*"
rand_core = "*"
dsv_writer = { git = "https://github.com/Tokeiya/dsv_writer.git", branch = "master" }
rayon = "*"
crossbeam-channel = "*"
common_errors = { git = "https://github.com/Tokeiya/common_errors", branch = "master" }
thiserror = "*"
dsv_reader = { git = "https://github.com/Tokeiya/dsv_reader.git", tag = "VER_0_4_1", package = "dsv_reader" }
postgres = "*"
clap = { version = "4.*", features = ["derive"] }
dashmap = "*"